const productsData = [{
        id: 1,
        name: "Agenda Disney",
        bid: 23500.00,
        prduct: "Agenda-disney",
        category: "Impresiones",
        cardImg: "./img/Productos/Agenda-disney.png",
    },
    {
        id: 2,
        name: "Cinta Adhesiva",
        bid: 1200.00,
        prduct: "Cinta-adhesiva",
        category: "Varios",
        cardImg: "./img/Productos/Cinta-adhesiva.png",
    },
    {
        id: 3,
        name: "Crayones Maped",
        bid: 1160.00,
        prduct: "crayones-color-peps-x-12-colores-maped",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/crayones-color-peps-x-12-colores-maped.jpg",
    },
    {
        id: 4,
        name: "Crayones Faber Castell",
        bid: 3300.00,
        prduct: "crayones-jumbo-x12-colores-faber-castell",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/crayones-jumbo-x12-colores-faber-castell.jpg",
    },
    {
        id: 5,
        name: "Cuaderno America A4",
        bid: 1250.00,
        prduct: "cuaderno-america-terra-A4",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/cuaderno-america-terra-A4.jpg",
    },
    {
        id: 6,
        name: "Escuadra Koh Noor",
        bid: 800.00,
        prduct: "Escuadra-Koh Noor-16Cm",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/Escuadra-Koh Noor-16Cm.jpg",
    },
    {
        id: 7,
        name: "Folios A4 10u",
        bid: 640.00,
        prduct: "Folios-a4-10u",
        category: "Varios",
        cardImg: "./img/Productos/Folios-a4.png",
    },
    {
        id: 8,
        name: "Goma de borrar Koh",
        bid: 580.00,
        prduct: "Goma-de-borrar-Koh",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/Goma-de-borrar-Koh.jpg",
    },
    {
        id: 9,
        name: "Ibi Crafts papeles",
        bid: 2300.00,
        prduct: "Ibi-craft",
        category: "Impresiones",
        cardImg: "./img/Productos/Ibi-craft.PNG",
    },
    {
        id: 10,
        name: "Lapiceras Faber Castell 5u",
        bid: 1500.00,
        prduct: "Lapiceras-Faber-Castell",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/Lapiceras-Faber-Castell.jpg",
    },
    {
        id: 11,
        name: "Lápices Filgo Colores",
        bid: 700.00,
        prduct: "lapices-filgo-colores",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/lapices-filgo-colores.jpg",
    },
    {
        id: 12,
        name: "Libreta Veterinaria",
        bid: 1100.00,
        prduct: "libreta-veterinaria",
        category: "Impresiones",
        cardImg: "./img/Productos/libreta-veterinaria.jpg",
    },
    {
        id: 13,
        name: "Mochila Barbie",
        bid: 25000.00,
        prduct: "Mochila-barbie",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/Mochila-barbie.PNG",
    },
    {
        id: 14,
        name: "Mochila Gamer",
        bid: 25000.00,
        prduct: "Mochila-gamer",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/Mochila-gamer.PNG",
    },
    {
        id: 15,
        name: "Mochila Joystick",
        bid: 25000.00,
        prduct: "Mochila-joystick",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/Mochila-joystick.PNG",
    },
    {
        id: 16,
        name: "Mochila Unicorns",
        bid: 25000.00,
        prduct: "Mochila-unicorns",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/Mochila-unicorns.PNG",
    },
    {
        id: 17,
        name: "Moños Regalo 100u",
        bid: 2200.00,
        prduct: "monos-regalo-100u",
        category: "Varios",
        cardImg: "./img/Productos/monos-regalo.jpg",
    },
    {
        id: 18,
        name: "Organizador Plástico",
        bid: 3400.00,
        prduct: "Organizador-Plastico-Vertical",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/Organizador-Plastico-Vertical.jpg",
    },
    {
        id: 19,
        name: "Post It Pastel",
        bid: 2400.00,
        prduct: "post-it-76x76-pastel-x400",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/post-it-76x76-pastel-x400.jpg",
    },
    {
        id: 20,
        name: "Recetario Cocina",
        bid: 800.00,
        prduct: "Recetario-cocina",
        category: "Impresiones",
        cardImg: "./img/Productos/Recetario-cocina.jpg",
    },
    {
        id: 21,
        name: "Resaltadores Faber Castell",
        bid: 7800.00,
        prduct: "Resaltadores-Faber-Castell-Textliner-Marcadores",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/Resaltadores-Faber-Castell-Textliner-Marcadores.png",
    },
    {
        id: 22,
        name: "Resma A4 Autor",
        bid: 2850.00,
        prduct: "Resma-a4-autor",
        category: "Varios",
        cardImg: "./img/Productos/Resma-a4.PNG",
    },
    {
        id: 23,
        name: "Sobre Manilla 10u",
        bid: 600.00,
        prduct: "Sobre-Manila-10u",
        category: "Varios",
        cardImg: "./img/Productos/Sobre-Manila.jpg",
    },
    {
        id: 24,
        name: "Tijera Olami",
        bid: 970.00,
        prduct: "Tijera-Mango-Plastico-Olami-100-Standard",
        category: "Articulos de libreria",
        cardImg: "./img/Productos/Tijera-Mango-Plastico-Olami-100-Standard.jpg",
    },

];

//función para dividir los productos en arrays de "size" productos
const divideProductsInParts = (size) => {
    let productsList = [];
    for (let i = 0; i < productsData.length; i += size)
        productsList.push(productsData.slice(i, i + size))
    return productsList;
};

//el concepto de ESTADO
const appState = {
    products: divideProductsInParts(9),
    currentProductsIndex: 0,
    productsLimit: divideProductsInParts(9).length,
    activeFilter: null
};